# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: master

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: 'src/assets/static/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads'

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'events'
    label: 'Events'
    folder: 'src/assets/content/events'
    create: true
    slug: '{{slug}}'
    widget: list
    format: 'json'
    fields:
      - { label: Title, name: title, widget: string , required: true  }
      - { label: Time, name: time, widget: datetime, required: true  }
      - { label: Description, name: description, widget: markdown }
      - { label: 'Image', name: featuredImage, widget: image, required: true  }
  - name: 'posts'
    label: 'Posts'
    folder: 'src/assets/content/posts'
    create: true
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: Title, name: title, widget: string , required: true }
      - { label: 'Published At', name: publishedAt, widget: date, required: true  }
      - { label: Content, name: description, widget: markdown , required: true }
      - { label: 'Main Image', name: featuredImage, widget: image, required: true }
      - { label: 'Image', name: galleryImages, widget: list, required: true ,summary: '{{fields.image}}',field: {label: Image, name: image, widget: image}}
  - name: 'obituaries'
    label: 'Obituaries'
    folder: 'src/assets/content/obituaries'
    create: true
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: Name, name: title, widget: string , required: true }
      - { label: Age, name: age, widget: number , required: true , value_type: "int", min: 1 , max: 101}
      - { label: Address, name: address, widget: markdown }
      - { label: 'Funeral At', name: funeralAt, widget: datetime , required: true }
      - { label: 'Died on', name: diedOn, widget: datetime , required: true }
      - { label: Description, name: description, widget: markdown, required: true}
      - { label: 'Photo', name: featuredImage, widget: image, required: true }
  - name: 'officeBearers'
    label: 'Parish Officers'
    folder: 'src/assets/content/officeBearers'
    create: false
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: 'Members', name: members, widget: list, required: true ,summary: '{{fields.image}}',fields: [{ label: Name, name: name, widget: string , required: true },{ label: Postion, name: postion, widget: string , required: true},{ label: Mobile, name: mobile, widget: string , required: false},{ label: Address, name: address, widget: string , required: true},{ label: Image, name: image, widget: image , required: true}]}
  - name: 'kaisthanasamithy'
    label: 'Kaisthanasamithy'
    folder: 'src/assets/content/kaisthanasamithy'
    create: false
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: 'Members', name: members, widget: list, required: true ,summary: '{{fields.image}}',fields: [{ label: Name, name: name, widget: string , required: true },{ label: Postion, name: postion, widget: string , required: true},{ label: Mobile, name: mobile, widget: string , required: true},{ label: Address, name: address, widget: string , required: true},{ label: Image, name: image, widget: image , required: true}]}
  - name: 'sexton'
    label: 'Sexton'
    folder: 'src/assets/content/sexton'
    create: false
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: 'Members', name: members, widget: list, required: true ,summary: '{{fields.image}}',fields: [{ label: Name, name: name, widget: string , required: true },{ label: Mobile, name: mobile, widget: string , required: true},{ label: Address, name: address, widget: string , required: true},{ label: Image, name: image, widget: image , required: true}]}
  - name: 'auditors'
    label: 'Auditors'
    folder: 'src/assets/content/auditors'
    create: false
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: 'Members', name: members, widget: list, required: true ,summary: '{{fields.image}}',fields: [{ label: Name, name: name, widget: string , required: true },{ label: Mobile, name: mobile, widget: string , required: true},{ label: Address, name: address, widget: string , required: true},{ label: Image, name: image, widget: image , required: true}]}
  - name: 'vicar'
    label: 'Vicar'
    folder: 'src/assets/content/vicar'
    create: false
    slug: '{{slug}}'
    format: 'json'
    fields:
       - { label: Name, name: name, widget: string , required: true }
       - { label: 'Start date', name: startDate, widget: date, required: true ,format: 'MMMM YYYY' }
       - { label: 'End date', name: endDate, widget: date, required: false ,format: 'MMMM YYYY' }
       - { label: Baskiamos , name: wife, widget: string , required: false }
       - { label: Childrens , name: childrens, widget: string , required: false }
