# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: master

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: 'src/assets/static/images/uploads' # Media files will be stored in the repo under images/uploads
public_folder: '/images/uploads'

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'events'
    label: 'Events'
    folder: 'src/assets/content/events'
    create: true
    slug: '{{slug}}'
    widget: list
    format: 'json'
    fields:
      - { label: Title, name: title, widget: string , required: true  }
      - { label: ID, name: id, widget: ncw-id , prefix: events , timestamp: true,required: true ,hint: This is an unique read-only id}
      - { label: Time, name: time, widget: datetime, required: true  }
      - { label: Description, name: description, widget: markdown }
      - { label: 'Image', name: featuredImage, widget: image, required: true  }
  - name: 'posts'
    label: 'Posts'
    folder: 'src/assets/content/posts'
    create: true
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: Title, name: title, widget: string , required: true }
      - { label: ID, name: id, widget: ncw-id , prefix: post , timestamp: true,required: true ,hint: This is an unique read-only id}
      - { label: 'Published At', name: publishedAt, widget: date, format: 'Do MMM YYYY', required: true  }
      - { label: Content, name: description, widget: markdown , required: true }
      - { label: 'Main Image', name: featuredImage, widget: image, required: true }
      - { label: 'Image', name: galleryImages, widget: list, required: true ,summary: '{{fields.image}}',field: {label: Image, name: image, widget: image}}
  - name: 'obituaries'
    label: 'Obituaries'
    folder: 'src/assets/content/obituaries'
    create: true
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: Name, name: name, widget: string , required: true }
      - { label: ID, name: id, widget: ncw-id , prefix: obituaries , timestamp: true,required: true ,hint: This is an unique read-only id}
      - { label: Age, name: age, widget: number , required: true , value_type: "int", min: 1 , max: 101}
      - { label: Address, name: address, widget: markdown }
      - { label: 'Funeral At', name: funeralAt, widget: datetime , required: true }
      - { label: About, name: about, widget: string}
  - name: 'officeBearers'
    label: 'Office Bearers'
    folder: 'src/assets/content/officeBearers'
    create: false
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: 'Office Bearers', name: members, widget: list, required: true ,summary: '{{fields.image}}',fields: [{ label: Name, name: name, widget: string , required: true },{ label: Postion, name: postion, widget: string , required: true},{ label: Mobile, name: mobile, widget: string , required: true},{ label: Address, name: address, widget: string , required: true},{ label: Image, name: image, widget: image , required: true}]}
  - name: 'kaisthanasamithy'
    label: 'Kaisthanasamithy'
    folder: 'src/assets/content/kaisthanasamithy'
    create: false
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: 'Kaisthanasamithy', name: members, widget: list, required: true ,summary: '{{fields.image}}',fields: [{ label: Name, name: name, widget: string , required: true },{ label: Postion, name: postion, widget: string , required: true},{ label: Mobile, name: mobile, widget: string , required: true},{ label: Address, name: address, widget: string , required: true},{ label: Image, name: image, widget: image , required: true}]}


